name: elixir-tour

services:
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: elixir
      POSTGRES_PASSWORD: elixir
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
volumes:
  db_data: 